//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AX_PROPED_DETALLE_PEDIDO
    {
        public int id_det_pedido { get; set; }
        public int id_pedido { get; set; }
        public Nullable<int> id_cia { get; set; }
        public string id_Co { get; set; }
        public string id_tipo_doc { get; set; }
        public string Pedido { get; set; }
        public string producto { get; set; }
        public string id_ref { get; set; }
        public string id_med { get; set; }
        public string id_ext_ref { get; set; }
        public string id_color_ref { get; set; }
        public string id_bodega { get; set; }
        public Nullable<int> id_concepto { get; set; }
        public string id_motivo { get; set; }
        public Nullable<int> ind_obsequio { get; set; }
        public string id_co_movto { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<int> num_dias_entrega { get; set; }
        public string id_lista_precio { get; set; }
        public string id_unidad_med { get; set; }
        public Nullable<decimal> cant_base { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<int> ind_impuestos_asumi { get; set; }
        public Nullable<int> ind_backorder { get; set; }
        public Nullable<int> ind_precio { get; set; }
        public string descripcion { get; set; }
    
        public virtual AX_PROPED_PEDIDO AX_PROPED_PEDIDO { get; set; }
    }
}
