//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AX_PROPED_OP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AX_PROPED_OP()
        {
            this.AX_PROPED_OP_CONSUMO = new HashSet<AX_PROPED_OP_CONSUMO>();
            this.AX_PROPED_OP_TIRAS = new HashSet<AX_PROPED_OP_TIRAS>();
        }
    
        public int id_OP { get; set; }
        public string id_Co { get; set; }
        public string id_tipo_doc { get; set; }
        public string conse_docto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string tercero_planifica { get; set; }
        public string notas { get; set; }
        public string sucursal { get; set; }
        public string cliente { get; set; }
        public string pedido { get; set; }
        public string producto { get; set; }
        public string color { get; set; }
        public string medida { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string lona { get; set; }
        public string planificador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AX_PROPED_OP_CONSUMO> AX_PROPED_OP_CONSUMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AX_PROPED_OP_TIRAS> AX_PROPED_OP_TIRAS { get; set; }
    }
}
