//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AX_PROPED_CONSU_TIRAS
    {
        public int id_insu { get; set; }
        public string ref_prod { get; set; }
        public string producto { get; set; }
        public string color_prod { get; set; }
        public string id_color_prod { get; set; }
        public string medida_prod { get; set; }
        public string id_medida_prod { get; set; }
        public Nullable<decimal> cant_tiras { get; set; }
        public decimal largo_tiras { get; set; }
        public string Lona { get; set; }
        public string color { get; set; }
    }
}
