//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AX_PROPED_OP_CONSUMO
    {
        public int id_consu { get; set; }
        public int id_OP { get; set; }
        public string num_op { get; set; }
        public string id_tipo_doc { get; set; }
        public string id_Co { get; set; }
        public string bodega_insu { get; set; }
        public string ref_insu { get; set; }
        public string insumo { get; set; }
        public string color_insu { get; set; }
        public Nullable<decimal> cant_insu { get; set; }
        public string uni_med { get; set; }
    
        public virtual AX_PROPED_OP AX_PROPED_OP { get; set; }
    }
}
