//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AX_PROPED_CONSU_ECO
    {
        public int id_insu { get; set; }
        public string ref_prod { get; set; }
        public string producto { get; set; }
        public string color_prod { get; set; }
        public string id_color_prod { get; set; }
        public string medida_prod { get; set; }
        public string id_medida_prod { get; set; }
        public string ref_insu { get; set; }
        public string insumo { get; set; }
        public string um_insu { get; set; }
        public string color_insu { get; set; }
        public string id_color_insu { get; set; }
        public decimal cant_insu { get; set; }
        public string tipo_insu { get; set; }
    }
}
