//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AX_PROPED_OP_TIRAS
    {
        public int id_tiras { get; set; }
        public int id_OP { get; set; }
        public string num_op { get; set; }
        public string id_tipo_doc { get; set; }
        public string id_Co { get; set; }
        public string lona { get; set; }
        public string color { get; set; }
        public Nullable<decimal> l_tiras { get; set; }
        public Nullable<decimal> n_tiras { get; set; }
        public Nullable<decimal> tmts_tiras { get; set; }
    
        public virtual AX_PROPED_OP AX_PROPED_OP { get; set; }
    }
}
