//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnoEEEntities : DbContext
    {
        public UnoEEEntities()
            : base("name=UnoEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AX_PROPED_CONSU_ECO> AX_PROPED_CONSU_ECO { get; set; }
        public virtual DbSet<AX_PROPED_CONSU_TIRAS> AX_PROPED_CONSU_TIRAS { get; set; }
        public virtual DbSet<AX_PROPED_DETALLE_PEDIDO> AX_PROPED_DETALLE_PEDIDO { get; set; }
        public virtual DbSet<AX_PROPED_OP> AX_PROPED_OP { get; set; }
        public virtual DbSet<AX_PROPED_OP_CONSUMO> AX_PROPED_OP_CONSUMO { get; set; }
        public virtual DbSet<AX_PROPED_OP_TIRAS> AX_PROPED_OP_TIRAS { get; set; }
        public virtual DbSet<AX_PROPED_PEDIDO> AX_PROPED_PEDIDO { get; set; }
    }
}
